[build.environment]
NODE_VERSION = "16"

[dev]
autoLaunch = false

[functions]

directory = "functions"
[build]
command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
publish = "build"

[[redirects]]
from = "*"
status = 404
to = "/404"
