[build.environment]
NODE_VERSION = "16"
NPM_FLAGS = "--version"

[dev]
autoLaunch = false

[functions]
directory = "functions"

[build]
publish = "build"

[[redirects]]
from = "*"
status = 404
to = "/404"
